
spring:
    mvc:
        view:
             # 定位模板的目录
            prefix: classpath:/templates/
            # 给返回的页面添加后缀名
            suffix: .html
            #静态资源访问
        static-path-pattern: /static/**

    datasource:
        url: jdbc:mysql://localhost:3306/Fanny?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456

    servlet:
      multipart:
        max-file-size: 10GB
        max-request-size: 10GB

mybatis :
    mapper-locations : classpath*:mybatis/Mapper/*Mapper.xml







